spring:
  datasource:
    url: jdbc:mysql://localhost:3306/programming
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    rest:
      base-path: /api

server:
  port: 5050
